// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVW1o4Krfe8c6A43wGRZ9UeLrNSto0ys',
    appId: '1:862972157521:web:4aedaeccf27165a18b6270',
    messagingSenderId: '862972157521',
    projectId: 'doit-app-aa699',
    authDomain: 'doit-app-aa699.firebaseapp.com',
    storageBucket: 'doit-app-aa699.firebasestorage.app',
    measurementId: 'G-MRK39079ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_wA1K7vs8kyxc6bPvMZtiacUAwUs7r8',
    appId: '1:862972157521:android:47a506c5a5d7ba1f8b6270',
    messagingSenderId: '862972157521',
    projectId: 'doit-app-aa699',
    storageBucket: 'doit-app-aa699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6s_3gu2TvCg4I1n_48TFItoXw65vTv6g',
    appId: '1:862972157521:ios:ec782438f1bfa52c8b6270',
    messagingSenderId: '862972157521',
    projectId: 'doit-app-aa699',
    storageBucket: 'doit-app-aa699.firebasestorage.app',
    iosBundleId: 'com.example.doitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6s_3gu2TvCg4I1n_48TFItoXw65vTv6g',
    appId: '1:862972157521:ios:ec782438f1bfa52c8b6270',
    messagingSenderId: '862972157521',
    projectId: 'doit-app-aa699',
    storageBucket: 'doit-app-aa699.firebasestorage.app',
    iosBundleId: 'com.example.doitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCVW1o4Krfe8c6A43wGRZ9UeLrNSto0ys',
    appId: '1:862972157521:web:2d8963b64150f01e8b6270',
    messagingSenderId: '862972157521',
    projectId: 'doit-app-aa699',
    authDomain: 'doit-app-aa699.firebaseapp.com',
    storageBucket: 'doit-app-aa699.firebasestorage.app',
    measurementId: 'G-NDQY799F0N',
  );
}
